#!/bin/bash
# add_bc_agents.sh — Run on Mac Mini via:
#   ssh mgat.agent@100.78.250.61 'bash -s' < add_bc_agents.sh
#
# What this does:
#   1. Adds 4 BC agents to report_generator.js
#   2. Updates sgat_check.sh cron minimum from 6 → 14
#   3. Runs sgat_check.sh to regenerate check_results.json
#   4. Git commits all changes
#
# Generated by ATLAS — 2026-05-24

set -e
SGAT_DIR="/Users/mgat.agent/sgat"

echo "=== [1/4] Patching report_generator.js ==="

cd "$SGAT_DIR"

# Show the current agents section so we know what we're working with
echo "--- Current agents array entries ---"
grep -n "SGAT_\|stateFile\|state_\|agents\s*=" report_generator.js | head -40
echo "---"

# Detect format and add the 4 BC agents
# Strategy: find last occurrence of a state_ reference and add after the block
# This handles both { name/stateFile } and inline string formats

python3 - <<'PYEOF'
import re, sys

filepath = "/Users/mgat.agent/sgat/report_generator.js"
with open(filepath, "r") as f:
    content = f.read()

new_agents = [
    ("SGAT_SOL_BC",  "/Users/mgat.agent/sgat/state_sol_bc.json"),
    ("SGAT_BASE_BC", "/Users/mgat.agent/sgat/state_base_bc.json"),
    ("SGAT_BSC_BC",  "/Users/mgat.agent/sgat/state_bsc_bc.json"),
    ("SGAT_SUI_BC",  "/Users/mgat.agent/sgat/state_sui_bc.json"),
]

# Check if agents already added
if "SGAT_SOL_BC" in content:
    print("BC agents already present in report_generator.js — skipping.")
    sys.exit(0)

# ── Try format 1: object array  { name: 'SGAT_XXX', stateFile: '...' }
obj_pattern = r"(\{[^}]*name\s*:\s*['\"]SGAT_\w+['\"][^}]*stateFile\s*:\s*['\"][^'\"]+['\"][^}]*\})"
matches = list(re.finditer(obj_pattern, content, re.DOTALL))
if matches:
    last = matches[-1]
    # Detect quote style and indent
    sample = last.group(0)
    indent = ""
    for ch in reversed(content[:last.start()]):
        if ch == "\n": break
        indent = ch + indent
    indent = re.match(r"^\s*", indent).group(0)
    quote = "'" if "'" in sample else '"'

    # Build new entries mirroring the existing format
    additions = ""
    for name, sf in new_agents:
        additions += f",\n{indent}{{ name: {quote}{name}{quote}, stateFile: {quote}{sf}{quote} }}"

    new_content = content[:last.end()] + additions + content[last.end():]
    with open(filepath, "w") as f:
        f.write(new_content)
    print(f"✅ Added 4 BC agents (object format) after '{matches[-1].group(0)[:40].strip()}...'")
    sys.exit(0)

# ── Try format 2: string array  'SGAT_XXX'  or  "SGAT_XXX"
str_pattern = r"(['\"])(SGAT_\w+)\1"
matches = list(re.finditer(str_pattern, content))
if matches:
    last = matches[-1]
    quote = last.group(1)
    additions = ""
    for name, _ in new_agents:
        additions += f", {quote}{name}{quote}"
    new_content = content[:last.end()] + additions + content[last.end():]
    with open(filepath, "w") as f:
        f.write(new_content)
    print(f"✅ Added 4 BC agents (string format) after '{last.group(0)}'")
    sys.exit(0)

# ── Format not recognised — print file excerpt and abort
print("❌ Could not find agents array pattern. File excerpt around 'SGAT_':")
for i, line in enumerate(content.splitlines()):
    if "SGAT_" in line:
        print(f"  L{i+1}: {line.strip()}")
sys.exit(1)
PYEOF

echo ""
echo "=== [2/4] Patching sgat_check.sh (cron min 6 → 14) ==="

if grep -q "SGAT_SOL_BC\|SGAT_BASE_BC" sgat_check.sh 2>/dev/null; then
    echo "sgat_check.sh already updated — skipping."
else
    # Show current cron-count line
    echo "--- Current cron check line ---"
    grep -n "6\|cron\|run_cycle\|trader" sgat_check.sh | head -20
    echo "---"
    # Replace the minimum count (6 → 14) — handles both -lt 6 and [ $x -lt 6 ] etc.
    sed -i.bak 's/-lt 6/-lt 14/g; s/< 6/< 14/g; s/min=6/min=14/g; s/minimum=6/minimum=14/g; s/CRON_MIN=6/CRON_MIN=14/g; s/CRON_MIN:-6/CRON_MIN:-14/g' sgat_check.sh
    echo "✅ Updated cron minimum to 14"
    echo "--- New cron check line ---"
    grep -n "14\|cron\|run_cycle\|trader" sgat_check.sh | head -20
fi

echo ""
echo "=== [3/4] Running sgat_check.sh to refresh check_results.json ==="
bash ~/sgat/sgat_check.sh > ~/sgat/check_results.json
echo "✅ check_results.json updated"
cat ~/sgat/check_results.json | python3 -c "import sys,json; d=json.load(sys.stdin); print(f'  PASSED: {d[\"passed\"]}  FAILED: {d[\"failed\"]}  STATUS: {d.get(\"all_systems_go\",\"?\")}')" 2>/dev/null || cat ~/sgat/check_results.json

echo ""
echo "=== [4/4] Git commit ==="
cd "$SGAT_DIR"
git add report_generator.js sgat_check.sh check_results.json
git commit -m "Add 4 BC agents to dashboard and check script"
echo "✅ Git commit done"

echo ""
echo "=== All done. Mac Mini changes complete. ==="
